config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get 'posts/:name' => 'posts#show', as: :page

 get 'pages/cities', as: :cities

 get ':city/weather' => 'pages#weather', as: :weather

end

app/models/City.rb
class City
  require 'open-uri'
  require 'json'
  attr_accessor :name, :country, :image, :content, :temp, :humidity, :rain, :text


  def initialize(name, country, image, content)
    @name = name
    @country = country
    @image = image
    @content = content
    @rain = rain
    @text = text
  end


  def forecast
    open("http://api.wunderground.com/api/088a807b8233bfad/geolookup/conditions/q/#{self.country}/#{self.name.gsub(' ', '_')}.json") do |f|
      json_string = f.read
      parsed_json = JSON.parse(json_string)
      @temp = parsed_json['current_observation']['temp_f']
      @humidity = parsed_json['current_observation']['relative_humidity']
    end

    open("http://api.wunderground.com/api/088a807b8233bfad/geolookup/forecast/q/#{self.country}/#{self.name.gsub(' ', '_')}.json") do |f|
      json_string = f.read
      parsed_json = JSON.parse(json_string)
      @rain = parsed_json['forecast']['txt_forecast']['forecastday'].first['pop']
      @text = parsed_json['forecast']['txt_forecast']['forecastday'].first['fcttext']
    end
  end
end

app/models/weather.rb
require 'open-uri'
require 'json'
open('http://api.wunderground.com/api/Your_Key/geolookup/conditions/q/IA/Cedar_Rapids.json') do |f|
  json_string = f.read
  parsed_json = JSON.parse(json_string)
  location = parsed_json['location']['city']
  temp_f = parsed_json['current_observation']['temp_f']
  print "Current temperature in #{location} is: #{temp_f}\n"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action do
    @cities = []
    @cities << City.new("Shanghai", "CN", "Shanghai.jpg","Shanghai")
    @cities << City.new("Karachi", "PK", "Karachi.jpg","Karachi")
    @cities << City.new("Beijing", "Beijing", "Beijing.jpg","Beijing")
    @cities << City.new("Tianjin", "CN", "Tianjin.jpg","Tianjin")
    @cities << City.new("Istanbul", "TU", "Istanbul.jpg","Istanbul")
    @cities << City.new("Lagos", "Nigeria", "Lagos.jpg","Lagos")
    @cities << City.new("Guangzhou","China", "Guangzhou.jpg","Guangzhou")
    @cities << City.new("Mumbai", "IN", "Mumbai.jpg","Mumbai")
    @cities << City.new("Dhaka", "Bangladesh", "Dhaka.jpg","Dhaka")
    @cities << City.new("Cairo", "EG", "Cairo.jpg","Cairo")
    @cities << City.new("Sao Paulo", "Brazil", "Sao-Paulo.jpg","Sao Paulo")
    @cities << City.new("Lahore","PK", "Lahore.jpg","Lahore")
    @cities << City.new("Seoul", "KR", "Seoul.jpg", "Seoul")
    @cities << City.new("Jakarta", "ID", "Jakarta.jpg", "Jakarta")
    @cities << City.new("Kinshasa", "Congo", "Kinshasa.jpg","Kinshasa")
    @cities << City.new("Tokyo", "JP", "Tokyo.jpg", "Tokyo")
    @cities << City.new("Mexico City", "MX", "Mexico-City.jpg","Mexico City")
    @cities << City.new("Lima","Peru", "Lima.jpg","Lima")
  end

  def cities
  end

  def weather
    @selected_city = @cities.find do |city|
      city.name == params[:city]
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  class Post
    attr_accessor :title, :image, :content

    def initialize(title, image, content)
      @title = title
      @image = image
      @content = content
    end
  end

  before_action do
    @posts = []
    @posts << Post.new("Another Cool Post", "another-cool-post.jpg", "Another Cool Post Content!!!")
    @posts << Post.new("Post Title", "post-title.jpg", "Post Title Content!!!")
    @posts << Post.new("Another Longer Post Title", "another-longer-post-title.jpg", "Another Longer Post Title Content!!!")
    @posts << Post.new("Oh Cool A Post!", "oh-cool-a-post.jpg", "Oh Cool A Post! Content!!!")
    @posts << Post.new("Most Interesting Post","most-interesting-post.jpg","Most Interesting Post Content!!!")
  end

  def index
    @selected_post = @posts.find {|post| post.title == "Most Interesting Post"}
    @other_posts = []
    @other_posts = @posts.select do |post|
      post.title != @selected_post.title
    end
  end

  def show
    @selected_post = @posts.find {|post| post.title == params[:name]}
    @other_posts = []
    @other_posts = @posts.select do |post|
      post.title != @selected_post.title
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Asap' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Ubuntu:300' rel='stylesheet' type='text/css'>
  <!-- Mobile Responsiveness? -->
    <meta name="viewport" content="width=320" />
  <title>Surf & Paddle Co.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="page">
      <header id="top">
        <div class="opacity">
          <nav>
            <ul>
              <%= image_tag"Logo.png", class:"logo"%>
              <li class="blog-title">SURF & PADDLE CO. BLOG</li>
              <li id="search" class="navright"><a href="searchfunction">SEARCH<%= image_tag"search.png" %></a></li>
              <li class="navright"><a href="About.html">ABOUT</a></li>
            </ul>
          </nav>
          <h1>SURF & PADDLE CO.</h1>
          <p>An Ironyard Academy Project Est. Fall 2013</p>
        </div>
      </header>
      <%= yield %>

</body>
</html>

app/views/pages/cities.html.erb
<h1>Surf & Paddle Co. Weather Check!</h1>
<ul class="weather">
  <% @cities.each do |city| %>
    <li><%= link_to city.name, weather_path(city: city.name) %></li>
  <% end %>
<ul>

app/views/pages/weather.html.erb
<div class="city" style="background: url(<%= image_url(@selected_city.image) %>); background-repeat: no-repeat;background-size: cover;">
  <%= link_to 'Home', cities_path %>
  <div class="background">
    <h1><%= @selected_city.name %></h1>
     <% @selected_city.forecast %>
     <h4>Temperature = <%= @selected_city.temp %></h4>
     <br>
     <h4>Humidity = <%= @selected_city.humidity %></h4>
     <br>
     <h4>Rain Chance = <%= @selected_city.rain %></h4>
     <br>
     <h4>Forecast = <%= @selected_city.text %></h4>
  </div>
</div>

app/views/posts/_body_html.html.erb
<div class="main-content">
  <article id="Content">
    <h2> <%= @selected_post.title || "Most Interesting Post"%> </h2>
    <p class="author"><%= image_tag"Anne-Icon.png"%>
      <a href="Annemarie.com">Anne Marie</a> on <span> Monday Oct. 7th 9:22pm</span>
    </p>
    <h3><%= @selected_post.content %></h3>
    <p>
       Wes Anderson umami street art Odd Future, Thundercats locavore plaid.
       Beard drinking vinegar photo booth Thundercats, hashtag Carles paleo
       trust fund polaroid kitsch mastercleanse banjo Etsy roof party butcher polaroid cardigan.
    </p>
    <p>
        Twee photo booth Carles, paleo Tumblr Portland normcore fixie street
        art polaroid cardigan aesthetic. PBR food truck you probably haven't
        heard of them, jean shorts Echo Park <a href="whateverseitan.com">whatever seitan</a>.
    </p>
    <blockquote><%= link_to "WOAH, THAT'S RADICAL! Check out the weather!", cities_path %></blockquote>
    <p>
      Pitchfork gluten-free flannel, narwhal umami chambray Brooklyn taxidermy
      sustainable paleo. Wolf chia small batch, DIY locavore wayfarers pug fap
      artisan cray fingerstache lo-fi. Dreamcatcher migas <a href="sriracha.com">
      sriracha</a> forage. Selvage twee ennui vegan, photo booth deep v Williamsburg
      cardigan mumblecore ugh PBR&B farm-to-table tattooed sustainable beard.
      Scenester cliche kitsch Austin, banjo flannel meditation next level Bushwick
      you probably haven't heard of them. YOLO cred kogi tote bag gluten-free
      Etsy viral. Forage cray cronut, cardigan readymade Shoreditch lomo Truffaut
      Tumblr meditation. Farm-to-table narwhal pug literally hashtag.
    </p>
    <p>
      Farm-to-table narwhal pug literally hashtag, locavore hella lomo.
      Mustache Shoreditch meditation, roof party Tumblr master cleanse farm-to-table
      fanny pack +1 scenester Intelligentsia listicle cliche. Tattooed taxidermy
      sustainable, semiotics sartorial Banksy.
    </p>
    <a href="Morecomments.com">
      <%= image_tag"Read-Comments-Icon.png"%><%= image_tag"Read-Comments-Text.png", class:"IconText"%>
    </a>
    </a>
    <a href="javascriptfunction">
      <%= image_tag"Read-Later-Icon.png"%><%= image_tag"Read-Later-Text.png", class:"IconText"%>
    </a>
    <a href="http://twitter.com/share?text=An%20Awesome%20Post&url=http://www.martinbee.github.io/week3">
      <%= image_tag"Share-Icon.png"%><%= image_tag"Share-Text.png", class:"IconText"%>
    </a>
  </article>
  <aside>
    <div class="profile">
      <%= image_tag"AnneMarie.png"%>
      <p><a href="Annemarie.com"><span>ANNE MARIE</span></a></p>
      <p><a href="twitter.com">Twitter</a> <a href="facebook.com">Facebook</a>
        <a href="instagram.com">Instagram</a>
      </p>
    </div>
    <%= image_tag"Lady.png", class:"lady"%>
    <a class="ad" href="paddleboardingisfun.com">About This Ad</a>
    <h2>SIDEBAR SECTION HEADING</h2>
    <p class="sidebartext">
      Twee photo booth Carles, paleo Tumblr Portland normcore fixie street
      art polaroid cardigan aesthetic. PBR food truck you probably haven't
      heard of them, jean shorts Echo Park <a class="seitan" href="whateverseitan.com">whatever seitan</a>.
      Narwhal pug literally hashtag, locavore hella lomo
      mustache.
    </p>
  </aside>
</div>
<div class="posts">
  <h2>MOST POPULAR POSTS</h2>
  <ul>
    <% @other_posts.each do |post| %>
        <%= link_to page_path(name: post.title) do %>
          <li style="background: url(<%= image_url(post.image) %>); background-repeat: no-repeat; background-size: cover;">
            <div class="opacity-posts">
              <%= post.title %>
            </div>
          </li>
        <% end %>
    <% end %>
  </ul>
</div>
<footer>
  <ul>
    <%= image_tag "TIY.png", class:"logo" %>
    <li class="copyright">The Ironyard Copyright 2013,<span> All Rights Reserved</span></li>
    <li id="lastfooteritem"class="footerright"><a href="#search">Search</a></li>
    <li class="footerright"><a href="About.html">About</a></li>
    <li class="footerright"><a href="#Content">Content</a></li>
    <li class="footerright"><a href="#top">Top</a></li>
  </ul>
</footer>
</div>

app/views/posts/index.html.erb
<%= render partial: 'body_html' %>

app/views/posts/show.html.erb
<%= render partial: 'body_html' %>